### ISSUE TITLE
Just a suggestion:

### ISSUE THREAD

**Issue by datenwolf** [pidcodes/pidcodes.github.com#38] opened 2015-04-04 18:23 UTC
I'd like to suggest to reserve a special PID for an idea I've been toying around lately (not for my use, but for everyone): One thing I never understood about the USB spec is, why Intel and Microsoft, who love GUIDs (look at OLE(2), COM and so on) used short 2·16 bit IDs for USB. The only explanation was/is, that this is a form of a cash grab. *USB would have been just as easy to implement using GUIDs for vendor and product.*

So the idea I had is the following: USB descriptors can carry additional data to the standard defined fields. Also there is support for arbitrary string descriptors. Reserving a special VID:PID pair could be associated with a custom "specification" that the actual vendor and product ID are to be retrieved from a dedicated string descriptor in the form of GUIDs. I've been doing this for some time now with VID:PID=0:0. I'd like to see that idea to spread.

**Comment by Arachnid** [comment] 2015-04-04 19:46
Duplicate of #33.

**Closed by Arachnid** 2015-04-04 19:46 UTC
